### ISSUE TITLE
Redstone related feature requests

### ISSUE THREAD

**Issue by Palmidence** [williambl/EssentialFeatures#1]
Not sure where the right place is to submit a feature request (no contributing guidelines) but I have some suggestions regarding redstone circuitry.
- [x] Ability to dye redstone torches, much like LEDs for color coding and nice looking builds.
- [x] Ender rods crafted with redstone (Redstone rods) that output a redstone signal when struck by lightning (attracting lightning). Can also be used to transmit a signal to other redstone in it's vicinity, like WiFi. Highly requested on the /r/minecraftsuggestions subreddit, and I can see practical uses for it.
- [x] Engineer villagers. These villagers have a red tinted apron and give pre-crafted redstone products to trade for in exchange for emeralds.
- [x] Stained redstone lamps. Put them in a crafting grid with a dye, and you get a colored lamp.

**Comment by williambl** [comment]
Yeah, this is the correct place.
1. Great idea
2. Great idea
3. Great idea
4. Do you mean just a different texture or actually coloured light? Because the latter would require recoding the entire lighting system, and that is not something I can do or want to do. But just a retexture is a great idea!

Thanks for the suggestions!

**Comment by Palmidence** [comment]
@williambl Definitely retexturing! And thanks.

**Comment by williambl** [comment]
Done the stained redstone lamps, now I'm adding your viewed block texture :D (thanks for that, btw. You'll be mentioned in the mod description)

**Comment by williambl** [comment]
Added your viewed block texture and mechanic villagers!

**Comment by Palmidence** [comment]
Thanks! :D

**Comment by williambl** [comment]
Finally, the first feature request is now complete, after 2 years!
