### ISSUE TITLE
Add cereal, crafted with 1 wheat, 1 milk, and 1 bowl

### ISSUE THREAD

**Issue by Palmidence** [williambl/EssentialFeatures#3]
**Texture:** ![](http://i.imgur.com/RAXa2dS.png)

**Usage:** Don't have any beets or mushrooms? Does bread not heal enough? You can now craft cereal. It heals as much as mushroom soup, and it's convinent for bringing on adventures.

![](https://i.gyazo.com/9a21fd6ce49bea17c689cae06007a8da.png)

**Crafting:**
x W x
x M x
x B x

x = empty slot
W = wheat
M = Milk
B = Bowl

**Comment by williambl** [comment]
Wow! I love it!
Definitely adding this.

**Comment by williambl** [comment]
Done!
