### ISSUE TITLE
Portable jukebox plays many tracks at once

### ISSUE THREAD

**Issue by Palmidence** [williambl/EssentialFeatures#31]
### Description: 

Portable jukebox plays many tracks at once

### Steps to reproduce the problem: 

Equip a portable jukebox and right click the ground numerous times to play the track.

### Expected behavior: 

It resets the song or has standard jukebox behavior.

### Actual behavior:  

Instead of that, it'll play 10 versions of the song at once if you click 10 times.

### Info:

Using latest forge, essentialfeatures, and Minecraft versions for 1.12.2. Tested in singleplayer.

**Comment by williambl** [comment]
Thanks for reporting.

This is one of the easier issues to fix: I know exactly why it's happening (the pjukebox doesn't check whether a track is currently playing before playing again) and that the solution is simple: stop all sounds, including pjukebox sounds, when the pjukebox starts playing. This will also have the good effect of removing any distracting background noise when the track starts.
