### ISSUE TITLE
Silk touch yielding seamless slabs instead of single slabs?

### ISSUE THREAD

**Issue by Palmidence** [williambl/EssentialFeatures#4]
Would be neat to be able to get double slabs and such as a block.

**Comment by williambl** [comment]
I don't really see the point in having a double-slab block in inventory. Just have a regular slab and place it twice. Or do you [mean](https://hydra-media.cursecdn.com/minecraft.gamepedia.com/0/05/Smooth_stone_slab.png) [seamless](https://hydra-media.cursecdn.com/minecraft.gamepedia.com/0/03/Smooth_Sandstone_Full_Half-Slab.png) [slabs](https://hydra-media.cursecdn.com/minecraft.gamepedia.com/d/d8/Full_Red_Sandstone_Slab.png)?

**Comment by Palmidence** [comment]
Seamless slabs!

**Comment by williambl** [comment]
I'm not sure... it doesn't really make sense. Perhaps a recipe for seamless slabs instead.

**Comment by williambl** [comment]
I'm going to do a recipe for seamless slabs instead.
