### ISSUE TITLE
Allow Blocks to be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [williambl/EssentialFeatures#71]
### Description:
Non-full blocks should be able to waterlog, such as the spike block or the slate layers.

### Info:

 - EssentialFeatures version: 3.0.1
 - Forge version: 28.1.87
 - Minecraft version: 1.14.4

**Comment by williambl** [comment]
![2019-11-15_16 33 07](https://user-images.githubusercontent.com/5115825/68959410-df07bf00-07c5-11ea-800a-be2548ffe5c4.png)

Done, it'll be in the next update (a couple of weeks maybe)

Thanks for pointing this out - I've noticed that you've opened similar issues in loads of other mods, you're doing the modding community a real service by finding these issues :D

**Comment by WenXin20** [comment]
No problem! It's enjoyable to help out!

**Comment by WenXin20** [comment]
Can the Transport Chute, Brazier, Hopper Filter, and hoppers be added as well? Just noticed these blocks.

**Comment by williambl** [comment]
Those are from [this mod](https://github.com/Da-Technomancer/Essentials), not my mod. It's a bit annoying how many mods have essential in their name, haha.

**Comment by WenXin20** [comment]
Oh whoops, you're right! Thanks!
