### ISSUE TITLE
Background Music Toggle for Config

### ISSUE THREAD

**Issue by McCarrick111** [williambl/EssentialFeatures#74]
I apologize if this is not related to your mod - but given the vague description of additional background tracks I believe it must be.

Since including your mod on our private server we've been having some extremely bizarre music occasionally play on its own. This music is metalic synth in nature, and frankly a lot of us find it all a bit too grating to be enjoyable.

I like the other features of your mod, but your config offers no means of removing the offending background tracks. Can such a means be implemented in the future?

On the 1.12.2 version to clarify.

**Comment by Palmidence** [comment]
The song metallic in nature is "give up" which plays in the ocean - it's a little grating in the context of other songs. If @williambl wants a replacement as opposed to this feature I wouldn't mind composing something more soft.

**Comment by williambl** [comment]
Fixed in v3.3.0.
