### ISSUE TITLE
Compatability issue with mods using tag forge:obsidian

### ISSUE THREAD

**Issue by wingwisher** [williambl/EssentialFeatures#81]
### Description:
mod version 3.2.0 for minecraft version 1.16.4 with forge 35.1.36 breaks recipies for mods that use block tag forge:obsidian
I'm unsure if this is the case for all mod recipies that use that tag, but it is an issue for multiple.

This does not result in a crash, but results in the items being uncraftable and a nullpointer being shown in JEI

pulled from the log while launching minecraft with essentialfeatures and mods that use that tag:
[Render thread/ERROR]: Couldn't load block tag forge:obsidian as it is missing following references: essentialfeatures:crying_obsidian (from essentialfeatures-3.2.0.jar)

A fix that seems to work is removing obsidian.json from both the mod's data/forge/tags/blocks folder and the mod's data/forge/tags/items folder

### Steps to reproduce the problem:
Run essentialfeatures alongside (example) blood magic and try to craft a master ritual stone (or use JEI to look up the recipe)
### Expected behavior:
obsidian in recipe
### Actual behavior: 
Null pointer in recipe, doesn't crash but does make the item unable to be crafted
Due to (pulled from log):

### Info:

 - EssentialFeatures version 3.2.0
 - Forge version 35.1.36
 - Minecraft version 1.16.4
 - Dedicated server, LAN game, or singleplayer? singleplayer
 - OS windows 10

**Comment by williambl** [comment]
Thanks for letting me know - looks like I forgot to remove the obsidian tag when I removed the crying obsidian block.
