### ISSUE TITLE
Portable Jukebox Dupe

### ISSUE THREAD

**Issue by GhostOfTheAshes** [williambl/EssentialFeatures#82]
### Description:
duplicates portable jukeboxes

### Steps to reproduce the problem:
place a stack of portable jukeboxes in crafting grid with one disc and shift click it into your inventory and you will get a stack of boxes with one disc inside and an empty stack of jukeboxes 

### Expected behavior:
get the same amount of jukeboxes you put into grid

### Actual behavior:
doubles the amount of jukeboxes you put into crafting grid 
### Info:

 - EssentialFeatures version
 - Forge version
 - 1.16.5 36.0.0
 - Minecraft version
 - 1.16.5
 - Dedicated server, LAN game, or singleplayer?
 - singleplayer
 - 
 - OS: windows

**Comment by GhostOfTheAshes** [comment]
also theres a dupe you can do with just a stack of portable jukeboxes and a chest

**Comment by williambl** [comment]
Fixed in v3.3.0.
